// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: neighbourhood.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Neighbourhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start           *int32                   `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	Nodes           []int32                  `protobuf:"varint,2,rep,name=nodes" json:"nodes,omitempty"`
	EdgeIndexSource []int32                  `protobuf:"varint,3,rep,name=edge_index_source,json=edgeIndexSource" json:"edge_index_source,omitempty"`
	EdgeIndexTarget []int32                  `protobuf:"varint,4,rep,name=edge_index_target,json=edgeIndexTarget" json:"edge_index_target,omitempty"`
	EdgeTypes       *Neighbourhood_EdgeTypes `protobuf:"bytes,5,opt,name=edge_types,json=edgeTypes" json:"edge_types,omitempty"`
}

func (x *Neighbourhood) Reset() {
	*x = Neighbourhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbourhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbourhood) ProtoMessage() {}

func (x *Neighbourhood) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbourhood.ProtoReflect.Descriptor instead.
func (*Neighbourhood) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0}
}

func (x *Neighbourhood) GetStart() int32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *Neighbourhood) GetNodes() []int32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Neighbourhood) GetEdgeIndexSource() []int32 {
	if x != nil {
		return x.EdgeIndexSource
	}
	return nil
}

func (x *Neighbourhood) GetEdgeIndexTarget() []int32 {
	if x != nil {
		return x.EdgeIndexTarget
	}
	return nil
}

func (x *Neighbourhood) GetEdgeTypes() *Neighbourhood_EdgeTypes {
	if x != nil {
		return x.EdgeTypes
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Neighbourhood `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetElements() []*Neighbourhood {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Neighbourhood_EdgeType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seen           *bool `protobuf:"varint,1,req,name=seen" json:"seen,omitempty"`
	Like           *bool `protobuf:"varint,2,req,name=like" json:"like,omitempty"`
	Reply          *bool `protobuf:"varint,3,req,name=reply" json:"reply,omitempty"`
	Retweet        *bool `protobuf:"varint,4,req,name=retweet" json:"retweet,omitempty"`
	RetweetComment *bool `protobuf:"varint,5,req,name=retweet_comment,json=retweetComment" json:"retweet_comment,omitempty"`
}

func (x *Neighbourhood_EdgeType) Reset() {
	*x = Neighbourhood_EdgeType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbourhood_EdgeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbourhood_EdgeType) ProtoMessage() {}

func (x *Neighbourhood_EdgeType) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbourhood_EdgeType.ProtoReflect.Descriptor instead.
func (*Neighbourhood_EdgeType) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Neighbourhood_EdgeType) GetSeen() bool {
	if x != nil && x.Seen != nil {
		return *x.Seen
	}
	return false
}

func (x *Neighbourhood_EdgeType) GetLike() bool {
	if x != nil && x.Like != nil {
		return *x.Like
	}
	return false
}

func (x *Neighbourhood_EdgeType) GetReply() bool {
	if x != nil && x.Reply != nil {
		return *x.Reply
	}
	return false
}

func (x *Neighbourhood_EdgeType) GetRetweet() bool {
	if x != nil && x.Retweet != nil {
		return *x.Retweet
	}
	return false
}

func (x *Neighbourhood_EdgeType) GetRetweetComment() bool {
	if x != nil && x.RetweetComment != nil {
		return *x.RetweetComment
	}
	return false
}

type Neighbourhood_EdgeTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes []*Neighbourhood_EdgeType `protobuf:"bytes,1,rep,name=attributes" json:"attributes,omitempty"`
}

func (x *Neighbourhood_EdgeTypes) Reset() {
	*x = Neighbourhood_EdgeTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbourhood_EdgeTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbourhood_EdgeTypes) ProtoMessage() {}

func (x *Neighbourhood_EdgeTypes) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbourhood_EdgeTypes.ProtoReflect.Descriptor instead.
func (*Neighbourhood_EdgeTypes) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Neighbourhood_EdgeTypes) GetAttributes() []*Neighbourhood_EdgeType {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_neighbourhood_proto protoreflect.FileDescriptor

var file_neighbourhood_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x03, 0x0a, 0x0d, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f,
	0x65, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x2a, 0x0a, 0x11, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f, 0x65, 0x64, 0x67, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x65,
	0x64, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e,
	0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x09, 0x65, 0x64, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x1a, 0x8b, 0x01, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x08, 0x52,
	0x04, 0x73, 0x65, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x08, 0x52, 0x04, 0x6c, 0x69, 0x6b, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70,
	0x6c, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x08,
	0x52, 0x07, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x74,
	0x77, 0x65, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x02,
	0x28, 0x08, 0x52, 0x0e, 0x72, 0x65, 0x74, 0x77, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x1a, 0x44, 0x0a, 0x09, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x37, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68,
	0x6f, 0x6f, 0x64, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x22, 0x33, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68,
	0x6f, 0x6f, 0x64, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
}

var (
	file_neighbourhood_proto_rawDescOnce sync.Once
	file_neighbourhood_proto_rawDescData = file_neighbourhood_proto_rawDesc
)

func file_neighbourhood_proto_rawDescGZIP() []byte {
	file_neighbourhood_proto_rawDescOnce.Do(func() {
		file_neighbourhood_proto_rawDescData = protoimpl.X.CompressGZIP(file_neighbourhood_proto_rawDescData)
	})
	return file_neighbourhood_proto_rawDescData
}

var file_neighbourhood_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_neighbourhood_proto_goTypes = []interface{}{
	(*Neighbourhood)(nil),           // 0: Neighbourhood
	(*Batch)(nil),                   // 1: Batch
	(*Neighbourhood_EdgeType)(nil),  // 2: Neighbourhood.EdgeType
	(*Neighbourhood_EdgeTypes)(nil), // 3: Neighbourhood.EdgeTypes
}
var file_neighbourhood_proto_depIdxs = []int32{
	3, // 0: Neighbourhood.edge_types:type_name -> Neighbourhood.EdgeTypes
	0, // 1: Batch.elements:type_name -> Neighbourhood
	2, // 2: Neighbourhood.EdgeTypes.attributes:type_name -> Neighbourhood.EdgeType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_neighbourhood_proto_init() }
func file_neighbourhood_proto_init() {
	if File_neighbourhood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neighbourhood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbourhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbourhood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbourhood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbourhood_EdgeType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbourhood_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbourhood_EdgeTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neighbourhood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neighbourhood_proto_goTypes,
		DependencyIndexes: file_neighbourhood_proto_depIdxs,
		MessageInfos:      file_neighbourhood_proto_msgTypes,
	}.Build()
	File_neighbourhood_proto = out.File
	file_neighbourhood_proto_rawDesc = nil
	file_neighbourhood_proto_goTypes = nil
	file_neighbourhood_proto_depIdxs = nil
}
