// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: neighbourhood.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Neighbourhood_EdgeType int32

const (
	Neighbourhood_SEEN            Neighbourhood_EdgeType = 0
	Neighbourhood_LIKE            Neighbourhood_EdgeType = 1
	Neighbourhood_RETWEET         Neighbourhood_EdgeType = 2
	Neighbourhood_REPLY           Neighbourhood_EdgeType = 3
	Neighbourhood_RETWEET_COMMENT Neighbourhood_EdgeType = 4
	Neighbourhood_FOLLOW          Neighbourhood_EdgeType = 5
	Neighbourhood_AUTHOR          Neighbourhood_EdgeType = 6
)

// Enum value maps for Neighbourhood_EdgeType.
var (
	Neighbourhood_EdgeType_name = map[int32]string{
		0: "SEEN",
		1: "LIKE",
		2: "RETWEET",
		3: "REPLY",
		4: "RETWEET_COMMENT",
		5: "FOLLOW",
		6: "AUTHOR",
	}
	Neighbourhood_EdgeType_value = map[string]int32{
		"SEEN":            0,
		"LIKE":            1,
		"RETWEET":         2,
		"REPLY":           3,
		"RETWEET_COMMENT": 4,
		"FOLLOW":          5,
		"AUTHOR":          6,
	}
)

func (x Neighbourhood_EdgeType) Enum() *Neighbourhood_EdgeType {
	p := new(Neighbourhood_EdgeType)
	*p = x
	return p
}

func (x Neighbourhood_EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Neighbourhood_EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_neighbourhood_proto_enumTypes[0].Descriptor()
}

func (Neighbourhood_EdgeType) Type() protoreflect.EnumType {
	return &file_neighbourhood_proto_enumTypes[0]
}

func (x Neighbourhood_EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Neighbourhood_EdgeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Neighbourhood_EdgeType(num)
	return nil
}

// Deprecated: Use Neighbourhood_EdgeType.Descriptor instead.
func (Neighbourhood_EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0, 0}
}

type Neighbourhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start           *int32                   `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	Nodes           []int32                  `protobuf:"varint,2,rep,name=nodes" json:"nodes,omitempty"`
	EdgeIndexSource []int32                  `protobuf:"varint,3,rep,name=edge_index_source,json=edgeIndexSource" json:"edge_index_source,omitempty"`
	EdgeIndexTarget []int32                  `protobuf:"varint,4,rep,name=edge_index_target,json=edgeIndexTarget" json:"edge_index_target,omitempty"`
	EdgeType        *Neighbourhood_EdgeTypes `protobuf:"bytes,5,opt,name=edge_type,json=edgeType" json:"edge_type,omitempty"`
}

func (x *Neighbourhood) Reset() {
	*x = Neighbourhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbourhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbourhood) ProtoMessage() {}

func (x *Neighbourhood) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbourhood.ProtoReflect.Descriptor instead.
func (*Neighbourhood) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0}
}

func (x *Neighbourhood) GetStart() int32 {
	if x != nil && x.Start != nil {
		return *x.Start
	}
	return 0
}

func (x *Neighbourhood) GetNodes() []int32 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Neighbourhood) GetEdgeIndexSource() []int32 {
	if x != nil {
		return x.EdgeIndexSource
	}
	return nil
}

func (x *Neighbourhood) GetEdgeIndexTarget() []int32 {
	if x != nil {
		return x.EdgeIndexTarget
	}
	return nil
}

func (x *Neighbourhood) GetEdgeType() *Neighbourhood_EdgeTypes {
	if x != nil {
		return x.EdgeType
	}
	return nil
}

type Batch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*Neighbourhood `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (x *Batch) Reset() {
	*x = Batch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{1}
}

func (x *Batch) GetElements() []*Neighbourhood {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Neighbourhood_EdgeTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EdgeType []Neighbourhood_EdgeType `protobuf:"varint,1,rep,name=edge_type,json=edgeType,enum=Neighbourhood_EdgeType" json:"edge_type,omitempty"`
}

func (x *Neighbourhood_EdgeTypes) Reset() {
	*x = Neighbourhood_EdgeTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighbourhood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighbourhood_EdgeTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighbourhood_EdgeTypes) ProtoMessage() {}

func (x *Neighbourhood_EdgeTypes) ProtoReflect() protoreflect.Message {
	mi := &file_neighbourhood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighbourhood_EdgeTypes.ProtoReflect.Descriptor instead.
func (*Neighbourhood_EdgeTypes) Descriptor() ([]byte, []int) {
	return file_neighbourhood_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Neighbourhood_EdgeTypes) GetEdgeType() []Neighbourhood_EdgeType {
	if x != nil {
		return x.EdgeType
	}
	return nil
}

var File_neighbourhood_proto protoreflect.FileDescriptor

var file_neighbourhood_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2, 0x02, 0x0a, 0x0d, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x6e, 0x6f,
	0x64, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x11, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f,
	0x65, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x2a, 0x0a, 0x11, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0f, 0x65, 0x64, 0x67, 0x65,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x35, 0x0a, 0x09, 0x65,
	0x64, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x45,
	0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x08, 0x65, 0x64, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x1a, 0x41, 0x0a, 0x09, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12,
	0x34, 0x0a, 0x09, 0x65, 0x64, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f,
	0x6f, 0x64, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x65, 0x64, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x63, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c,
	0x49, 0x4b, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x54, 0x57, 0x45, 0x45, 0x54,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x10, 0x03, 0x12, 0x13, 0x0a,
	0x0f, 0x52, 0x45, 0x54, 0x57, 0x45, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54,
	0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x4f, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x05, 0x12, 0x0a,
	0x0a, 0x06, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x10, 0x06, 0x22, 0x33, 0x0a, 0x05, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x12, 0x2a, 0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75,
	0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
}

var (
	file_neighbourhood_proto_rawDescOnce sync.Once
	file_neighbourhood_proto_rawDescData = file_neighbourhood_proto_rawDesc
)

func file_neighbourhood_proto_rawDescGZIP() []byte {
	file_neighbourhood_proto_rawDescOnce.Do(func() {
		file_neighbourhood_proto_rawDescData = protoimpl.X.CompressGZIP(file_neighbourhood_proto_rawDescData)
	})
	return file_neighbourhood_proto_rawDescData
}

var file_neighbourhood_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_neighbourhood_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_neighbourhood_proto_goTypes = []interface{}{
	(Neighbourhood_EdgeType)(0),     // 0: Neighbourhood.EdgeType
	(*Neighbourhood)(nil),           // 1: Neighbourhood
	(*Batch)(nil),                   // 2: Batch
	(*Neighbourhood_EdgeTypes)(nil), // 3: Neighbourhood.EdgeTypes
}
var file_neighbourhood_proto_depIdxs = []int32{
	3, // 0: Neighbourhood.edge_type:type_name -> Neighbourhood.EdgeTypes
	1, // 1: Batch.elements:type_name -> Neighbourhood
	0, // 2: Neighbourhood.EdgeTypes.edge_type:type_name -> Neighbourhood.EdgeType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_neighbourhood_proto_init() }
func file_neighbourhood_proto_init() {
	if File_neighbourhood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neighbourhood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbourhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbourhood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Batch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighbourhood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighbourhood_EdgeTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neighbourhood_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_neighbourhood_proto_goTypes,
		DependencyIndexes: file_neighbourhood_proto_depIdxs,
		EnumInfos:         file_neighbourhood_proto_enumTypes,
		MessageInfos:      file_neighbourhood_proto_msgTypes,
	}.Build()
	File_neighbourhood_proto = out.File
	file_neighbourhood_proto_rawDesc = nil
	file_neighbourhood_proto_goTypes = nil
	file_neighbourhood_proto_depIdxs = nil
}
