// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: social_neighbourhood.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocialNetworkNeighbourhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SocialNeighbourhood  *Neighbourhood `protobuf:"bytes,1,req,name=social_neighbourhood,json=socialNeighbourhood" json:"social_neighbourhood,omitempty"`
	ContentNeighbourhood *Neighbourhood `protobuf:"bytes,2,req,name=content_neighbourhood,json=contentNeighbourhood" json:"content_neighbourhood,omitempty"`
}

func (x *SocialNetworkNeighbourhood) Reset() {
	*x = SocialNetworkNeighbourhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_neighbourhood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialNetworkNeighbourhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialNetworkNeighbourhood) ProtoMessage() {}

func (x *SocialNetworkNeighbourhood) ProtoReflect() protoreflect.Message {
	mi := &file_social_neighbourhood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialNetworkNeighbourhood.ProtoReflect.Descriptor instead.
func (*SocialNetworkNeighbourhood) Descriptor() ([]byte, []int) {
	return file_social_neighbourhood_proto_rawDescGZIP(), []int{0}
}

func (x *SocialNetworkNeighbourhood) GetSocialNeighbourhood() *Neighbourhood {
	if x != nil {
		return x.SocialNeighbourhood
	}
	return nil
}

func (x *SocialNetworkNeighbourhood) GetContentNeighbourhood() *Neighbourhood {
	if x != nil {
		return x.ContentNeighbourhood
	}
	return nil
}

type SocialNetworkBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Elements []*SocialNetworkNeighbourhood `protobuf:"bytes,1,rep,name=elements" json:"elements,omitempty"`
}

func (x *SocialNetworkBatch) Reset() {
	*x = SocialNetworkBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_social_neighbourhood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocialNetworkBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialNetworkBatch) ProtoMessage() {}

func (x *SocialNetworkBatch) ProtoReflect() protoreflect.Message {
	mi := &file_social_neighbourhood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialNetworkBatch.ProtoReflect.Descriptor instead.
func (*SocialNetworkBatch) Descriptor() ([]byte, []int) {
	return file_social_neighbourhood_proto_rawDescGZIP(), []int{1}
}

func (x *SocialNetworkBatch) GetElements() []*SocialNetworkNeighbourhood {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_social_neighbourhood_proto protoreflect.FileDescriptor

var file_social_neighbourhood_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x6e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x1a, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64,
	0x12, 0x41, 0x0a, 0x14, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x13,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68,
	0x6f, 0x6f, 0x64, 0x12, 0x43, 0x0a, 0x15, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f,
	0x6f, 0x64, 0x52, 0x14, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x22, 0x4d, 0x0a, 0x12, 0x53, 0x6f, 0x63, 0x69,
	0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x37,
	0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x53, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x75, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x08, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73,
}

var (
	file_social_neighbourhood_proto_rawDescOnce sync.Once
	file_social_neighbourhood_proto_rawDescData = file_social_neighbourhood_proto_rawDesc
)

func file_social_neighbourhood_proto_rawDescGZIP() []byte {
	file_social_neighbourhood_proto_rawDescOnce.Do(func() {
		file_social_neighbourhood_proto_rawDescData = protoimpl.X.CompressGZIP(file_social_neighbourhood_proto_rawDescData)
	})
	return file_social_neighbourhood_proto_rawDescData
}

var file_social_neighbourhood_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_social_neighbourhood_proto_goTypes = []interface{}{
	(*SocialNetworkNeighbourhood)(nil), // 0: SocialNetworkNeighbourhood
	(*SocialNetworkBatch)(nil),         // 1: SocialNetworkBatch
	(*Neighbourhood)(nil),              // 2: Neighbourhood
}
var file_social_neighbourhood_proto_depIdxs = []int32{
	2, // 0: SocialNetworkNeighbourhood.social_neighbourhood:type_name -> Neighbourhood
	2, // 1: SocialNetworkNeighbourhood.content_neighbourhood:type_name -> Neighbourhood
	0, // 2: SocialNetworkBatch.elements:type_name -> SocialNetworkNeighbourhood
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_social_neighbourhood_proto_init() }
func file_social_neighbourhood_proto_init() {
	if File_social_neighbourhood_proto != nil {
		return
	}
	file_neighbourhood_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_social_neighbourhood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialNetworkNeighbourhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_social_neighbourhood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocialNetworkBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_social_neighbourhood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_social_neighbourhood_proto_goTypes,
		DependencyIndexes: file_social_neighbourhood_proto_depIdxs,
		MessageInfos:      file_social_neighbourhood_proto_msgTypes,
	}.Build()
	File_social_neighbourhood_proto = out.File
	file_social_neighbourhood_proto_rawDesc = nil
	file_social_neighbourhood_proto_goTypes = nil
	file_social_neighbourhood_proto_depIdxs = nil
}
