# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neighbourhood.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neighbourhood.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13neighbourhood.proto\"\xae\x02\n\rNeighbourhood\x12\r\n\x05start\x18\x01 \x02(\x05\x12\r\n\x05nodes\x18\x02 \x03(\x05\x12\x19\n\x11\x65\x64ge_index_source\x18\x03 \x03(\x05\x12\x19\n\x11\x65\x64ge_index_target\x18\x04 \x03(\x05\x12+\n\tedge_type\x18\x05 \x01(\x0b\x32\x18.Neighbourhood.EdgeTypes\x1a\x37\n\tEdgeTypes\x12*\n\tedge_type\x18\x01 \x03(\x0e\x32\x17.Neighbourhood.EdgeType\"c\n\x08\x45\x64geType\x12\x08\n\x04SEEN\x10\x00\x12\x08\n\x04LIKE\x10\x01\x12\x0b\n\x07RETWEET\x10\x02\x12\t\n\x05REPLY\x10\x03\x12\x13\n\x0fRETWEET_COMMENT\x10\x04\x12\n\n\x06\x46OLLOW\x10\x05\x12\n\n\x06\x41UTHOR\x10\x06\")\n\x05\x42\x61tch\x12 \n\x08\x65lements\x18\x01 \x03(\x0b\x32\x0e.Neighbourhood'
)



_NEIGHBOURHOOD_EDGETYPE = _descriptor.EnumDescriptor(
  name='EdgeType',
  full_name='Neighbourhood.EdgeType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SEEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LIKE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETWEET', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPLY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RETWEET_COMMENT', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FOLLOW', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTHOR', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=227,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_NEIGHBOURHOOD_EDGETYPE)


_NEIGHBOURHOOD_EDGETYPES = _descriptor.Descriptor(
  name='EdgeTypes',
  full_name='Neighbourhood.EdgeTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='edge_type', full_name='Neighbourhood.EdgeTypes.edge_type', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=225,
)

_NEIGHBOURHOOD = _descriptor.Descriptor(
  name='Neighbourhood',
  full_name='Neighbourhood',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Neighbourhood.start', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Neighbourhood.nodes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_index_source', full_name='Neighbourhood.edge_index_source', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_index_target', full_name='Neighbourhood.edge_index_target', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_type', full_name='Neighbourhood.edge_type', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NEIGHBOURHOOD_EDGETYPES, ],
  enum_types=[
    _NEIGHBOURHOOD_EDGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=326,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='Batch.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=369,
)

_NEIGHBOURHOOD_EDGETYPES.fields_by_name['edge_type'].enum_type = _NEIGHBOURHOOD_EDGETYPE
_NEIGHBOURHOOD_EDGETYPES.containing_type = _NEIGHBOURHOOD
_NEIGHBOURHOOD.fields_by_name['edge_type'].message_type = _NEIGHBOURHOOD_EDGETYPES
_NEIGHBOURHOOD_EDGETYPE.containing_type = _NEIGHBOURHOOD
_BATCH.fields_by_name['elements'].message_type = _NEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['Neighbourhood'] = _NEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Neighbourhood = _reflection.GeneratedProtocolMessageType('Neighbourhood', (_message.Message,), {

  'EdgeTypes' : _reflection.GeneratedProtocolMessageType('EdgeTypes', (_message.Message,), {
    'DESCRIPTOR' : _NEIGHBOURHOOD_EDGETYPES,
    '__module__' : 'neighbourhood_pb2'
    # @@protoc_insertion_point(class_scope:Neighbourhood.EdgeTypes)
    })
  ,
  'DESCRIPTOR' : _NEIGHBOURHOOD,
  '__module__' : 'neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:Neighbourhood)
  })
_sym_db.RegisterMessage(Neighbourhood)
_sym_db.RegisterMessage(Neighbourhood.EdgeTypes)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  })
_sym_db.RegisterMessage(Batch)


# @@protoc_insertion_point(module_scope)
