# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neighbourhood.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neighbourhood.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13neighbourhood.proto\"\xac\x02\n\rNeighbourhood\x12\r\n\x05start\x18\x01 \x02(\x05\x12\r\n\x05nodes\x18\x02 \x03(\x05\x12\x19\n\x11\x65\x64ge_index_source\x18\x03 \x03(\x05\x12\x19\n\x11\x65\x64ge_index_target\x18\x04 \x03(\x05\x12,\n\nedge_types\x18\x05 \x01(\x0b\x32\x18.Neighbourhood.EdgeTypes\x1a_\n\x08\x45\x64geType\x12\x0c\n\x04seen\x18\x01 \x02(\x08\x12\x0c\n\x04like\x18\x02 \x02(\x08\x12\r\n\x05reply\x18\x03 \x02(\x08\x12\x0f\n\x07retweet\x18\x04 \x02(\x08\x12\x17\n\x0fretweet_comment\x18\x05 \x02(\x08\x1a\x38\n\tEdgeTypes\x12+\n\nattributes\x18\x01 \x03(\x0b\x32\x17.Neighbourhood.EdgeType\")\n\x05\x42\x61tch\x12 \n\x08\x65lements\x18\x01 \x03(\x0b\x32\x0e.Neighbourhood'
)




_NEIGHBOURHOOD_EDGETYPE = _descriptor.Descriptor(
  name='EdgeType',
  full_name='Neighbourhood.EdgeType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='seen', full_name='Neighbourhood.EdgeType.seen', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='like', full_name='Neighbourhood.EdgeType.like', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reply', full_name='Neighbourhood.EdgeType.reply', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retweet', full_name='Neighbourhood.EdgeType.retweet', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retweet_comment', full_name='Neighbourhood.EdgeType.retweet_comment', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=266,
)

_NEIGHBOURHOOD_EDGETYPES = _descriptor.Descriptor(
  name='EdgeTypes',
  full_name='Neighbourhood.EdgeTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='attributes', full_name='Neighbourhood.EdgeTypes.attributes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=324,
)

_NEIGHBOURHOOD = _descriptor.Descriptor(
  name='Neighbourhood',
  full_name='Neighbourhood',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='Neighbourhood.start', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Neighbourhood.nodes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_index_source', full_name='Neighbourhood.edge_index_source', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_index_target', full_name='Neighbourhood.edge_index_target', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='edge_types', full_name='Neighbourhood.edge_types', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NEIGHBOURHOOD_EDGETYPE, _NEIGHBOURHOOD_EDGETYPES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=324,
)


_BATCH = _descriptor.Descriptor(
  name='Batch',
  full_name='Batch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='Batch.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=367,
)

_NEIGHBOURHOOD_EDGETYPE.containing_type = _NEIGHBOURHOOD
_NEIGHBOURHOOD_EDGETYPES.fields_by_name['attributes'].message_type = _NEIGHBOURHOOD_EDGETYPE
_NEIGHBOURHOOD_EDGETYPES.containing_type = _NEIGHBOURHOOD
_NEIGHBOURHOOD.fields_by_name['edge_types'].message_type = _NEIGHBOURHOOD_EDGETYPES
_BATCH.fields_by_name['elements'].message_type = _NEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['Neighbourhood'] = _NEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['Batch'] = _BATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Neighbourhood = _reflection.GeneratedProtocolMessageType('Neighbourhood', (_message.Message,), {

  'EdgeType' : _reflection.GeneratedProtocolMessageType('EdgeType', (_message.Message,), {
    'DESCRIPTOR' : _NEIGHBOURHOOD_EDGETYPE,
    '__module__' : 'neighbourhood_pb2'
    # @@protoc_insertion_point(class_scope:Neighbourhood.EdgeType)
    })
  ,

  'EdgeTypes' : _reflection.GeneratedProtocolMessageType('EdgeTypes', (_message.Message,), {
    'DESCRIPTOR' : _NEIGHBOURHOOD_EDGETYPES,
    '__module__' : 'neighbourhood_pb2'
    # @@protoc_insertion_point(class_scope:Neighbourhood.EdgeTypes)
    })
  ,
  'DESCRIPTOR' : _NEIGHBOURHOOD,
  '__module__' : 'neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:Neighbourhood)
  })
_sym_db.RegisterMessage(Neighbourhood)
_sym_db.RegisterMessage(Neighbourhood.EdgeType)
_sym_db.RegisterMessage(Neighbourhood.EdgeTypes)

Batch = _reflection.GeneratedProtocolMessageType('Batch', (_message.Message,), {
  'DESCRIPTOR' : _BATCH,
  '__module__' : 'neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:Batch)
  })
_sym_db.RegisterMessage(Batch)


# @@protoc_insertion_point(module_scope)
