# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: social_neighbourhood.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import neighbourhood_pb2 as neighbourhood__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='social_neighbourhood.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asocial_neighbourhood.proto\x1a\x13neighbourhood.proto\"y\n\x1aSocialNetworkNeighbourhood\x12,\n\x14social_neighbourhood\x18\x01 \x02(\x0b\x32\x0e.Neighbourhood\x12-\n\x15\x63ontent_neighbourhood\x18\x02 \x02(\x0b\x32\x0e.Neighbourhood\"C\n\x12SocialNetworkBatch\x12-\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x1b.SocialNetworkNeighbourhood'
  ,
  dependencies=[neighbourhood__pb2.DESCRIPTOR,])




_SOCIALNETWORKNEIGHBOURHOOD = _descriptor.Descriptor(
  name='SocialNetworkNeighbourhood',
  full_name='SocialNetworkNeighbourhood',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='social_neighbourhood', full_name='SocialNetworkNeighbourhood.social_neighbourhood', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content_neighbourhood', full_name='SocialNetworkNeighbourhood.content_neighbourhood', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=172,
)


_SOCIALNETWORKBATCH = _descriptor.Descriptor(
  name='SocialNetworkBatch',
  full_name='SocialNetworkBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='elements', full_name='SocialNetworkBatch.elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=241,
)

_SOCIALNETWORKNEIGHBOURHOOD.fields_by_name['social_neighbourhood'].message_type = neighbourhood__pb2._NEIGHBOURHOOD
_SOCIALNETWORKNEIGHBOURHOOD.fields_by_name['content_neighbourhood'].message_type = neighbourhood__pb2._NEIGHBOURHOOD
_SOCIALNETWORKBATCH.fields_by_name['elements'].message_type = _SOCIALNETWORKNEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['SocialNetworkNeighbourhood'] = _SOCIALNETWORKNEIGHBOURHOOD
DESCRIPTOR.message_types_by_name['SocialNetworkBatch'] = _SOCIALNETWORKBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocialNetworkNeighbourhood = _reflection.GeneratedProtocolMessageType('SocialNetworkNeighbourhood', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALNETWORKNEIGHBOURHOOD,
  '__module__' : 'social_neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:SocialNetworkNeighbourhood)
  })
_sym_db.RegisterMessage(SocialNetworkNeighbourhood)

SocialNetworkBatch = _reflection.GeneratedProtocolMessageType('SocialNetworkBatch', (_message.Message,), {
  'DESCRIPTOR' : _SOCIALNETWORKBATCH,
  '__module__' : 'social_neighbourhood_pb2'
  # @@protoc_insertion_point(class_scope:SocialNetworkBatch)
  })
_sym_db.RegisterMessage(SocialNetworkBatch)


# @@protoc_insertion_point(module_scope)
